### ISSUE TITLE
【报错】不能涩涩了

### ISSUE THREAD

**Issue by Z735803792** [Special-Week/nonebot_plugin_setu4#22]
对了用的是清楚版的
```
10-12 18:45:54 [ERROR] nonebot | Running matcher <Matcher from src.plugins.nonebot_plugin_setu4, type=message, priority=10, temp=False> failed.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/usr/lib/python3.9/multiprocessing/spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
  File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.9/dist-packages/uvicorn/_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/usr/local/lib/python3.9/dist-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.9/dist-packages/nonebot/message.py", line 146, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "/usr/local/lib/python3.9/dist-packages/nonebot/message.py", line 196, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/usr/local/lib/python3.9/dist-packages/nonebot/internal/matcher.py", line 672, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/usr/local/lib/python3.9/dist-packages/nonebot/internal/matcher.py", line 639, in simple_run
    await handler(
  File "/usr/local/lib/python3.9/dist-packages/nonebot/dependencies/__init__.py", line 92, in __call__
    return await self.call(**values)
  File "/home/unb/nb2/src/plugins/nonebot_plugin_setu4/__init__.py", line 126, in _
    data = await get_setu(key, r18, num, quality)
  File "/home/unb/nb2/src/plugins/nonebot_plugin_setu4/get_data.py", line 56, in get_setu
    data = await asyncio.gather(*tasks)
  File "/home/unb/nb2/src/plugins/nonebot_plugin_setu4/get_data.py", line 64, in pic
    setu_url = setu[11].replace('i.pixiv.cat', 'i.pixiv.re')
IndexError: tuple index out of range
```

**Comment by Special-Week** [comment]
你这代码像是很旧的版本了, 我中途改过一次数据库表结构, 你把最新的代码clone一下

**Comment by Z735803792** [comment]
可以涩涩啦感谢
